name: Welcome first time contributors

on:
  pull_request_target:
    types: 
      - opened
  issues:
    types:
      - opened

jobs:
  welcome:
    name: Post welcome message
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install
        run: npm install

      - name: Run welcome script
        run: node .github/scripts/welcome-first-time-contributor.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

